repos:
-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
    -   id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        entry: mypy -p mimir
        language: system
        types: [python]
        pass_filenames: false
